{
  "version": 2,
  "builds": [
    {
      "src": "public/**",
      "use": "@vercel/static"
    },
    {
      "src": "functions/*.js",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/api/.*",
      "dest": "/functions"
    },
    {
      "src": "/(.*)",
      "dest": "/public/$1"
    }
  ]
}
